# Generated by Django 3.0.3 on 2020-04-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renewal',
        ),
        migrations.DeleteModel(
            name='Renewal_Response',
        ),
    ]
