# Generated by Django 3.0.2 on 2020-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
    ]
