# Generated by Django 3.0.3 on 2020-04-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200423_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal_Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_description', models.CharField(max_length=100, verbose_name='Response Description')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('renewal_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_date', models.DateField()),
                ('sent_date_2', models.DateField()),
                ('phone_call', models.BooleanField()),
                ('cust_locker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cust_Locker')),
                ('response_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response1', to='database.Renewal_Response')),
                ('response_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response2', to='database.Renewal_Response')),
                ('response_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response3', to='database.Renewal_Response')),
            ],
        ),
    ]
