# Generated by Django 3.0.3 on 2020-03-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200218_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='station',
            new_name='station_id',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='main_type',
            new_name='main_type_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_street',
        ),
        migrations.RemoveField(
            model_name='loc_maintenance',
            name='locker',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_address',
            field=models.CharField(default='', max_length=50, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='loc_maintenance',
            name='locker_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Locker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cust_loc',
            name='cust_loc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cust_loc_event',
            name='cust_loc_event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cust_status',
            name='cust_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cust_status_type',
            name='cust_stat_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_f_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_l_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_zip',
            field=models.CharField(max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_status',
            name='event_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loc_maintenance',
            name='loc_main_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='main_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenance_type',
            name='main_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
