# Generated by Django 3.0.3 on 2020-04-23 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_renewal_renewal_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker_Usage',
            fields=[
                ('locker_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('lu_description', models.CharField(max_length=100, verbose_name='Locker Usage')),
            ],
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='phone_call',
        ),
        migrations.AddField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 23, 20, 56, 21, 660077), verbose_name='Phone Call Date'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='response_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response1', to='database.Renewal_Response'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='response_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response2', to='database.Renewal_Response'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='response_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response3', to='database.Renewal_Response'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='sent_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='sent_date_2',
            field=models.DateField(blank=True),
        ),
    ]
