# Generated by Django 3.0.3 on 2020-03-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200301_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry_Loc',
            fields=[
                ('inquiry_loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Inquiry')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('status_desc', models.CharField(max_length=100, verbose_name='Status Description')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cust_Loc',
            new_name='Cust_Locker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_status_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type_id',
        ),
        migrations.RemoveField(
            model_name='loc_maintenance',
            name='locker_id',
        ),
        migrations.RenameField(
            model_name='cust_locker',
            old_name='cust_loc_id',
            new_name='cust_lock_id',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='main_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='main_id',
            new_name='maintenance_id',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='main_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='cust_status',
            name='cust_status_type_id',
        ),
        migrations.RemoveField(
            model_name='cust_status',
            name='station_id',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='locker_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Locker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance_type',
            name='main_type_desc',
            field=models.CharField(max_length=100, verbose_name='Maintenance Type Description'),
        ),
        migrations.DeleteModel(
            name='Cust_Loc_Event',
        ),
        migrations.DeleteModel(
            name='Cust_Status_Type',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_Status',
        ),
        migrations.DeleteModel(
            name='Event_Type',
        ),
        migrations.DeleteModel(
            name='Loc_Maintenance',
        ),
        migrations.AddField(
            model_name='cust_status',
            name='status_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Status'),
            preserve_default=False,
        ),
    ]
