# Generated by Django 3.0.3 on 2020-03-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200301_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_county',
        ),
    ]
