# Generated by Django 3.0.3 on 2020-04-24 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200424_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='locker_capacity',
        ),
        migrations.AddField(
            model_name='location',
            name='location_capacity',
            field=models.IntegerField(default=0, verbose_name='Location Capacity'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 24, 4, 4, 53, 611777), verbose_name='Phone Call Date'),
        ),
    ]
