# Generated by Django 3.0.3 on 2020-03-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_station_station_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('location_zip', models.CharField(max_length=10, verbose_name='Location Zip')),
            ],
        ),
        migrations.RemoveField(
            model_name='locker',
            name='station_id',
        ),
        migrations.DeleteModel(
            name='Inquiry_Loc',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='locations',
            field=models.ManyToManyField(to='database.Location'),
        ),
        migrations.AddField(
            model_name='locker',
            name='location_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Location'),
            preserve_default=False,
        ),
    ]
