# Generated by Django 3.0.3 on 2020-04-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200307_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cust_locker',
            options={'verbose_name': 'Customer Locker', 'verbose_name_plural': 'Customer Lockers'},
        ),
        migrations.AlterModelOptions(
            name='cust_status',
            options={'verbose_name': 'Customer Status', 'verbose_name_plural': 'Customer Statuses'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='maintenance_type',
            options={'verbose_name': 'Maintenance Type', 'verbose_name_plural': 'Maintenance Types'},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='locker_id',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='location_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_description',
            field=models.CharField(default='', max_length=250, verbose_name='Maintenance Description'),
        ),
        migrations.CreateModel(
            name='Maintenance_Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker', models.ManyToManyField(to='database.Locker')),
                ('maintenance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Maintenance')),
            ],
        ),
    ]
