# Generated by Django 3.0.3 on 2020-03-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200307_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cust_locker',
            options={'verbose_name': 'Customer Locker', 'verbose_name_plural': 'Customer Lockers'},
        ),
        migrations.AlterModelOptions(
            name='cust_status',
            options={'verbose_name': 'Customer Status', 'verbose_name_plural': 'Customer Statuses'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='maintenance_type',
            options={'verbose_name': 'Maintenance Type', 'verbose_name_plural': 'Maintenance Types'},
        ),
    ]
