# Generated by Django 3.0.3 on 2020-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200402_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='isWholeLocation',
            field=models.BooleanField(default=1, verbose_name='Maintenance on the general facility (vs. specific lockers)?'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='lockers',
            field=models.ManyToManyField(blank=True, to='database.Locker'),
        ),
        migrations.DeleteModel(
            name='Maintenance_Locker',
        ),
    ]
