# Generated by Django 3.0.3 on 2020-04-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_waitlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cust_l_name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone'),
        ),
    ]
