# Generated by Django 3.0.3 on 2020-04-24 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200424_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker_log',
            old_name='customer_id',
            new_name='cust_id',
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 24, 5, 0, 5, 498232, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
