# Generated by Django 3.0.3 on 2020-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200402_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_type',
            name='main_type_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Maintenance Type'),
        ),
    ]
