# Generated by Django 3.0.3 on 2020-04-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200408_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100, verbose_name='Key Name')),
                ('locker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Locker')),
            ],
        ),
        migrations.CreateModel(
            name='Key_Status',
            fields=[
                ('key_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_status_name', models.CharField(max_length=100, verbose_name='Key Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Locker_Status',
            fields=[
                ('locker_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('locker_status_name', models.CharField(max_length=100, verbose_name='Locker Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Status',
            fields=[
                ('main_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_status_name', models.CharField(max_length=100, verbose_name='Maintenance Status Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Cust_Status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
