# Generated by Django 3.0.3 on 2020-04-25 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200424_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_desc',
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 25, 8, 57, 56, 412401, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=100, verbose_name='Status Description'),
        ),
    ]
