# Generated by Django 3.0.3 on 2020-04-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200409_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key_status',
            options={'verbose_name': 'Key Status', 'verbose_name_plural': 'Key Statuses'},
        ),
        migrations.AlterModelOptions(
            name='locker_status',
            options={'verbose_name': 'Locker Status', 'verbose_name_plural': 'Locker Statuses'},
        ),
        migrations.AlterModelOptions(
            name='maintenance_status',
            options={'verbose_name': 'Maintenance Status', 'verbose_name_plural': 'Maintenance Statuses'},
        ),
        migrations.AddField(
            model_name='key',
            name='key_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Key_Status'),
        ),
        migrations.AddField(
            model_name='locker',
            name='locker_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Locker_Status'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='main_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Maintenance_Status'),
        ),
    ]
