# Generated by Django 3.0.3 on 2020-04-28 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200425_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 32, 33, 270323, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
