# Generated by Django 3.0.3 on 2020-05-06 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200428_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contacted',
            field=models.CharField(blank=True, default='Not Contacted', max_length=50, verbose_name='Contacted'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 6, 20, 41, 45, 714283, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
