# Generated by Django 3.0.3 on 2020-05-03 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200428_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 3, 1, 41, 20, 154766, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
