# Generated by Django 3.0.3 on 2020-05-05 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200502_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_locker',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 5, 3, 30, 6, 26923, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
