# Generated by Django 3.0.6 on 2020-05-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200506_2041'),
        ('database', '0016_auto_20200504_2030'),
    ]

    operations = [
    ]
