# Generated by Django 3.0.6 on 2020-05-07 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20200507_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_form',
            name='name_lease',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 7, 9, 59, 5, 418760, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
