# Generated by Django 3.0.6 on 2020-05-07 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20200507_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 7, 10, 8, 29, 402496, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
        migrations.AlterField(
            model_name='renewal_form',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='renewal_form',
            name='name_lease',
            field=models.CharField(default='', max_length=50, verbose_name='Name On Lease'),
        ),
    ]
