# Generated by Django 3.0.6 on 2020-05-07 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20200507_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 7, 10, 37, 45, 350720, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
        migrations.AlterField(
            model_name='renewal_form',
            name='renewal_decision',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Renewal Decision'),
        ),
    ]
