# Generated by Django 3.0.6 on 2020-05-11 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20200511_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker_renew_date',
            name='locker_renew_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 11, 17, 3, 7, 465325, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
