# Generated by Django 3.0.3 on 2020-05-07 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200507_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 7, 21, 5, 19, 960634, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
