# Generated by Django 3.0.6 on 2020-05-11 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200511_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='renewal_date',
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 11, 17, 3, 21, 89568, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
