# Generated by Django 3.0.6 on 2020-05-11 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20200511_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_locker',
            name='location_renewal_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Location_Renew'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 11, 23, 48, 11, 581177, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
