# Generated by Django 3.0.6 on 2020-05-11 23:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20200511_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_locker',
            old_name='location_renewal_date',
            new_name='location_renewal',
        ),
        migrations.AddField(
            model_name='location',
            name='location_renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Location_Renew'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 11, 23, 50, 23, 665615, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
