# Generated by Django 3.0.6 on 2020-05-11 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20200511_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Renewals',
            fields=[
                ('location_renew_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_renew_name', models.CharField(max_length=100, verbose_name='Location Renewal Name')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 11, 23, 55, 12, 754198, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
        migrations.AddField(
            model_name='cust_locker',
            name='location_renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Location_Renewals'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_renewal_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Location_Renewals'),
        ),
    ]
