# Generated by Django 3.0.3 on 2020-05-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20200512_0318'),
        ('database', '0031_auto_20200507_1405'),
    ]

    operations = [
    ]
