# Generated by Django 3.0.3 on 2020-05-12 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_merge_20200512_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cust_locker',
            options={'ordering': ['locker_id__location_id__location_name', 'cust_id__cust_l_name'], 'verbose_name': 'Customer Locker', 'verbose_name_plural': 'Customer Lockers'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AlterModelOptions(
            name='location_renewals',
            options={'verbose_name': 'Locker Location Renewal Date', 'verbose_name_plural': 'Locker Location Renewal Dates'},
        ),
        migrations.AlterField(
            model_name='location_renewals',
            name='date',
            field=models.DateField(null=True, verbose_name='Locker Location Renewal Date'),
        ),
        migrations.AlterField(
            model_name='location_renewals',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Location'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 12, 18, 41, 56, 690010, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
