# Generated by Django 3.0.6 on 2020-05-13 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20200513_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_locker',
            name='renew_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 13, 4, 59, 58, 418316, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
