# Generated by Django 3.0.6 on 2020-05-13 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20200513_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_locker',
            name='renew_date',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 13, 5, 3, 32, 6131, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
