# Generated by Django 3.0.6 on 2020-05-13 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_auto_20200513_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 13, 5, 17, 31, 104753, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
