# Generated by Django 3.0.3 on 2020-05-13 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20200513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 13, 18, 11, 13, 820451, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
