# Generated by Django 3.0.3 on 2020-05-13 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20200513_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_locker',
            old_name='description',
            new_name='key_number',
        ),
        migrations.AlterField(
            model_name='renewal',
            name='phone_call_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 13, 18, 39, 2, 915857, tzinfo=utc), verbose_name='Phone Call Date'),
        ),
    ]
